baseURL = "https://blog.mhfay.de/"
title = "Manny's Blog"
theme = "hugo-coder"
languageCode = "en"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Manuel-Hubertus Fay"
  description = "Your blog description"
  keywords = "blog,developer,personal"
  info = ["Software Engineer • Command Liner • Automation Lover"]
  # avatarURL = "images/avatar.jpg"  # optional
  colorScheme = "auto"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github"
  weight = 1
  url = "https://github.com/MannyFay/"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-twitter"
  weight = 2
  url = "https://twitter.com/FayManny/"

[languages.en]
  languageName = "English"

[[languages.en.menu.main]]
  name = "POSTS"
  weight = 1
  url = "posts/"

[[languages.en.menu.main]]
  name = "TAGS"
  weight = 2
  url = "tags/"

[[languages.en.menu.main]]
  name = "ABOUT"
  weight = 3
  url = "about/"

[[languages.en.menu.main]]
  name = "SITE NOTICE"
  weight = 4
  url = "site-notice/"
